/**
 * Catálogo de provincias y ciudades de la Argentina TAL COMO LAS CONOCE
 * MERCADO LIBRE / MERCADO PAGO.
 *
 * ⛔ NO SE EDITA A MANO. ⛔
 *
 * Este archivo NO es "la lista de localidades argentinas": es el catálogo
 * CONTRA EL QUE MERCADO PAGO VALIDA `location.state_name` y
 * `location.city_name` al vincular un estacionamiento. Agregarle una
 * localidad que MP no conoce —por más que exista en la vida real, por más que
 * la devuelva Georef, por más que el INDEC la liste— hace que la vinculación
 * falle con:
 *
 *     location.city_name was invalid
 *
 * Eso es exactamente el bug que este archivo vino a arreglar: el
 * estacionamiento tenía `city_name: "Martínez"`, MP no conoce "Martínez"
 * (conoce "San Isidro" y "Beccar"), y la vinculación se caía. Cambiando el
 * valor a "San Isidro" el error desapareció — confirmado en producción.
 *
 * Por eso tampoco se "corrigen" las mayúsculas raras que trae MELI
 * ("12 De Octubre", "4 DE noviembre"): MP compara contra SU string, no contra
 * el que nos parece prolijo.
 *
 * ── Procedencia ──────────────────────────────────────────────────────────
 * Generado desde la API pública de MercadoLibre:
 *
 *     GET https://api.mercadolibre.com/countries/AR    → states[] (id, name)
 *     GET https://api.mercadolibre.com/states/{id}     → cities[] (name)
 *
 * 24 provincias · 1046 ciudades. Sin duplicados y sin provincias
 * vacías. Ordenado alfabéticamente con `Intl.Collator('es')` —por eso
 * "Córdoba" va antes que "Corrientes"— para que los selectores se lean como
 * los espera una persona, no como los ordena UTF-8.
 *
 * ── Por qué va EMBEBIDO y no se fetchea ──────────────────────────────────
 * 15,2 KB minificado / 6,3 KB gzipped. A ese tamaño embeberlo es estrictamente
 * mejor que pedirlo por red: cero loading, cero manejo de error, cero CORS,
 * cero rate limit. La regla del `AddressPicker` —"NUNCA queda trabado"— se
 * cumple POR CONSTRUCCIÓN en vez de por código defensivo: no hay servicio que
 * se pueda caer.
 *
 * ── Si hay que regenerarlo ───────────────────────────────────────────────
 * Sólo cuando MP rechace una localidad que su catálogo ya debería tener. Se
 * regenera ENTERO desde la API de arriba; no se parchea a mano.
 */

/**
 * Provincia → sus ciudades. Las claves y los valores son los strings EXACTOS
 * de MELI, con sus tildes y su capitalización original.
 */
export const AR_LOCATION_CATALOG: Readonly<Record<string, readonly string[]>> =
  {
    'Buenos Aires': [
      '12 De Octubre',
      '25 de Mayo',
      '4 DE noviembre',
      '9 de Julio',
      'Adela',
      'Adolfo Alsina',
      'Adolfo Gonzales Chaves',
      'Aeropuerto Ezeiza',
      'Aguara',
      'Aguas Verdes',
      'Alagon',
      'Alberti',
      'Alegre',
      'Alejandro Korn',
      'Almirante Brown',
      'Alsina',
      'Alto Los Cardales',
      'Amalia',
      'Araujo',
      'Arrecifes',
      'Arroyo Aleli',
      'Arroyo Pareja',
      'Arturo Segui',
      'Arturo Vatteone',
      'Atucha',
      'Avellaneda',
      'Ayacucho',
      'Azul',
      'Bahía Blanca',
      'Balcarce',
      'Baradero',
      'Base Aeronaval Cmte Espora',
      'Base Aeronaval Punta Indio',
      'Base Naval Rio Santiago',
      'Baterias',
      'Beccar',
      'Benito Juárez',
      'Berazategui',
      'Berisso',
      'Beruti',
      'Blaquier',
      'Bolívar',
      'Boulogne',
      'Bragado',
      'Brandsen',
      'Cabildo',
      'Calfucura',
      'Campana',
      'Cañada La Rica',
      'Cañuelas',
      'Capitán Sarmiento',
      'Cariló',
      'Carlos Casares',
      'Carlos Tejedor',
      'Carmen de Areco',
      'Caseros',
      'Castelar',
      'Castelli',
      'Centro Agricola El Pato',
      'Chacabuco',
      'Chapadmalal',
      'Chascomús',
      'Chivilcoy',
      'Ciudad Jardin Del Palomar',
      'Coliqueo',
      'Colman',
      'Colón',
      'Comandante Giribone',
      'Cooper',
      'Coronel Dorrego',
      'Coronel Granada',
      'Coronel Pringles',
      'Coronel Rosales',
      'Coronel Suárez',
      'Costa Chica',
      'Costa del Este',
      'Costa Esmeralda',
      'Cuartel Iv',
      'Cucha Cucha',
      'Daireaux',
      'Del Viso',
      'Dique Luján',
      'Dolores',
      'Don Torcuato',
      'Dos Hermanos',
      'Drabble',
      'El Durazno',
      'El Espinillo',
      'El Perdido Est Jose Guisasola',
      'El Pino',
      'El Socorro',
      'El Trio',
      'Emilio Lamarca',
      'Ensenada',
      'Esc Nav Militar Rio Sant',
      'Escobar',
      'Espartillar',
      'Estacion Lago Epecuen',
      'Estacion Moreno',
      'Estancia Las Gamas',
      'Estancias',
      'Esteban De Luca',
      'Esteban Echeverría',
      'Exaltación de la Cruz',
      'Ezeiza',
      'Flamenco',
      'Florencio Varela',
      'Florentino Ameghino',
      'Fortin Irene',
      'Fortin Lavalle',
      'Garro',
      'General Alvarado',
      'General Alvear',
      'General Arenales',
      'General Belgrano',
      'General Daniel Cerri',
      'General Guido',
      'General La Madrid',
      'General Las Heras',
      'General Lavalle',
      'General Madariaga',
      'General Paz',
      'General Pinto',
      'General Pueyrredón',
      'General Rodríguez',
      'General San Martín',
      'General Viamonte',
      'General Villegas',
      'Guaminí',
      'Hipólito Yrigoyen',
      'Hurlingham',
      'Ingeniero Allan',
      'Ingeniero Budge',
      'Ingeniero De Madrid',
      'Ingeniero Williams',
      'Ireneo Portela',
      'Isla Los Laureles',
      'Isla Martin Garcia',
      'Ituzaingó',
      'José C. Paz',
      'Jose Clemente Paz',
      'Jose Ferrari',
      'Jose Leon Suarez',
      'Juancho',
      'Junín',
      'La Caleta',
      'La Colina',
      'La Dorita',
      'La Esperanza (ROSAS, PDO.LAS FLORES)',
      'La Lonja',
      'La Lucila del Mar',
      'La Matanza',
      'La Pastora',
      'La Plata',
      'La Querencia',
      'La Viticola',
      'Lanús',
      'Laprida',
      'Las Flores',
      'Las Toninas',
      'Leandro N. Alem',
      'Leubuco',
      'Lincoln',
      'Lobería',
      'Lobos',
      'Lomas de Zamora',
      'Los Cardales',
      'Luján',
      'Magdalena',
      'Maipú',
      'Malvinas Argentinas',
      'Manuel Alberti',
      'Manuel B Gonnet',
      'Mar Azul',
      'Mar Chiquita',
      'Mar de Ajo',
      'Mar De Cobo',
      'Mar de las Pampas',
      'Mar del Plata',
      'Mar del Sur',
      'Mar del Tuyu',
      'Marcos Paz',
      'Masurel',
      'Mecha',
      'Mercedes',
      'Merlo',
      'Miramar',
      'Monte',
      'Monte Hermoso',
      'Moreno',
      'Morón',
      'Navarro',
      'Necochea',
      'Olavarría',
      'Ostende',
      'Palantelen',
      'Patagones',
      'Pehuajó',
      'Pellegrini',
      'Pergamino',
      'Pila',
      'Pilar',
      'Pinamar',
      'Presidente Perón',
      'Primera Junta',
      'Puán',
      'Punta Indio',
      'Punta Lara',
      'Punta Médanos',
      'Quilmes',
      'Quiñihual Estacion',
      'Ramallo',
      'Ranchos',
      'Rauch',
      'Remedios De Escalada',
      'Rio Tala',
      'Rivadavia',
      'Rojas',
      'Roque Pérez',
      'Saavedra',
      'Saladillo',
      'Salliqueló',
      'Salto',
      'San Andres',
      'San Andrés de Giles',
      'San Antonio de Areco',
      'San Bernardo',
      'San Bernardo Del Tuyu',
      'San Cayetano',
      'San Clemente',
      'San Clemente Del Tuyu',
      'San Fernando',
      'San Isidro',
      'San Miguel',
      'San Nicolás',
      'San Pedro',
      'San Vicente',
      'Santa Clara del Mar',
      'Santa Teresita',
      'Suipacha',
      'Tandil',
      'Tapalqué',
      'Tigre',
      'Tordillo',
      'Tornquist',
      'Trenque Lauquen',
      'Tres Arroyos',
      'Tres de febrero',
      'Tres Lomas',
      'Valeria del Mar',
      'Verónica',
      'Vicente López',
      'Villa Adelina',
      'Villa Gesell',
      'Villa Numancia',
      'Villa Robles',
      'Villarino',
      'Wilde',
      'Zárate',
      'Zona Delta San Fernando',
      'Zona Delta Tigre',
    ],
    'Capital Federal': [
      'Agronomía',
      'Almagro',
      'Balvanera',
      'Barracas',
      'Barrio Norte',
      'Belgrano',
      'Belgrano Barrancas',
      'Belgrano C',
      'Belgrano Chico',
      'Belgrano R',
      'Boedo',
      'Botánico',
      'Caballito',
      'Chacarita',
      'Coghlan',
      'Colegiales',
      'Constitución',
      'Flores',
      'Floresta',
      'La Boca',
      'Las Cañitas',
      'Liniers',
      'Mataderos',
      'Monserrat',
      'Monte Castro',
      'Nueva Pompeya',
      'Núñez',
      'Palermo',
      'Palermo Chico',
      'Palermo Hollywood',
      'Palermo Nuevo',
      'Palermo Soho',
      'Palermo Viejo',
      'Parque Avellaneda',
      'Parque Chacabuco',
      'Parque Chas',
      'Parque Patricios',
      'Paternal',
      'Puerto Madero',
      'Recoleta',
      'Retiro',
      'Saavedra',
      'San Cristóbal',
      'San Nicolás',
      'San Telmo',
      'Santa Rita',
      'Velez Sarsfield',
      'Versailles',
      'Villa Crespo',
      'Villa del Parque',
      'Villa Devoto',
      'Villa Gral. Mitre',
      'Villa Lugano',
      'Villa Luro',
      'Villa Ortúzar',
      'Villa Pueyrredón',
      'Villa Real',
      'Villa Riachuelo',
      'Villa Soldati',
      'Villa Urquiza',
    ],
    Catamarca: [
      'Ambato',
      'Ancasti',
      'Andalgalá',
      'Antofagasta de la Sierra',
      'Belén',
      'Brea Chimpana',
      'Capayán',
      'Cortaderas',
      'El Alto',
      'Fray Mamerto Esquiú',
      'La Paz',
      'Paclín',
      'Pomán',
      'San Fernando del Valle de Catamarca',
      'San Jose De Piedra Blanca',
      'Santa María',
      'Santa Rosa',
      'Tinogasta',
      'Valle Viejo',
    ],
    Chaco: [
      '12 de Octubre',
      '1º de Mayo',
      '2 de Abril',
      '25 de Mayo',
      '9 de Julio',
      'Almirante Brown',
      'Barranqueras',
      'Basail',
      'Bermejo',
      'Campo De Galnasi',
      'Chacabuco',
      'Comandante Fernández',
      'Curandu',
      'El Campamento',
      'Fray Justo Santa María de Oro',
      'General Belgrano',
      'General Donovan',
      'General Güemes',
      'Independencia',
      'Kilometro 184',
      'Libertad',
      'Libertador General San Martín',
      'Maipú',
      'Mayor Luis Jorge Fontana',
      'O Higgins',
      'Pozo Navagan',
      'Presidencia de la Plaza',
      'Quitilipi',
      'Resistencia',
      'Roque Saenz Peña',
      'San Lorenzo',
      'Sargento Cabral',
      'Tapenagá',
    ],
    Chubut: [
      'Bahia Solano',
      'Biedma',
      'Cañadon Lagarto',
      'Cerro Radal',
      'Colhue Huapi',
      'Cushamen',
      'El Porvenir',
      'Escalante',
      'Florentino Ameghino',
      'Futaleufú',
      'Gaiman',
      'Gastre',
      'Languiñeo',
      'Mártires',
      'Ñorquinco Sud',
      'Paso de Indios',
      'Rawson',
      'Río Senguer',
      'Sarmiento',
      'Tehuelches',
      'Telsen',
      'Valle Hondo',
    ],
    Córdoba: [
      'Achiras',
      'Agua Del Tala',
      'Alejandro Roca',
      'Alta Gracia',
      'Anisacate',
      'Aromito',
      'Arroyito',
      'Arroyo Santa Catalina',
      'Bengolea',
      'Berrotarán',
      'Bialet Massé',
      'Buey Muerto',
      'Calamuchita',
      'Calchin',
      'Calchin Oeste',
      'Campo Ambroggio',
      'Campo Bandillo',
      'Canteras Los Morales',
      'Capilla del Monte',
      'Casa Serrana Huerta Grande',
      'Cerro Bola',
      'Colón',
      'Colonia Coyunda',
      'Colonia Dolores',
      'Colonia El Fortin',
      'Colonia La Carmensita',
      'Colonia Maipu',
      'Colonia Santa Rita',
      'Colonia Valle Grande',
      'Colonia Videla',
      'Córdoba',
      'Corral Del Bajo',
      'Corralito',
      'Corralito San Javier',
      'Cosquín',
      'Cruz Alta',
      'Cruz del Eje',
      'Dalmacio Velez Sarsfield',
      'Dique Los Molinos',
      'El Pozo',
      'Est Candelaria Norte',
      'Freyre',
      'Galpon Chico',
      'General Deheza',
      'General Roca',
      'General San Martín',
      'Hospital Flia Domingo Funes',
      'Independencia',
      'Ischilín',
      'Jesús María',
      'Juárez Celman',
      'Kilometro 57',
      'La Aguada',
      'La Bolsa',
      'La Calera',
      'La Carlota',
      'La Falda',
      'La Oscuridad',
      'La Paisanita',
      'La Penca',
      'La Pintada',
      'Laguna Larga',
      'Lagunilla',
      'Los Espinillos',
      'Malagueño',
      'Marcos Juárez',
      'Mendiolaza',
      'Mina Clavero',
      'Minas',
      'Oncativo',
      'Ongamira',
      'Paunero',
      'Pocho',
      'Potrero de Garay',
      'Presidente Roque Sáenz Peña',
      'Puerto del Aguila',
      'Punilla',
      'Recreo Victoria',
      'Río Ceballos',
      'Río Cuarto',
      'Río Primero',
      'Río Seco',
      'Río Segundo',
      'San Alberto',
      'San Francisco',
      'San Javier',
      'San Justo',
      'San Marcos Sud',
      'Santa María',
      'Santa Rosa de Calamuchita',
      'Sobremonte',
      'Tercero Arriba',
      'Totoral',
      'Tulumba',
      'Ucacha',
      'Unión',
      'Villa Allende',
      'Villa Carlos Paz',
      'Villa General Belgrano',
      'Villa María',
      'Villa Santa Rosa',
      'Villa Suiza Argentina',
      'Yacanto',
    ],
    Corrientes: [
      'Arroyo Garay',
      'Arroyo Sarandi',
      'Arroyo Seco',
      'Bacacay',
      'Bañado San Antonio',
      'Bella Vista',
      'Berón de Astrada',
      'Carrizal Norte',
      'Concepción',
      'Corrientes',
      'Costa Grande',
      'Curuzú Cuatiá',
      'El Remanso',
      'Empedrado',
      'Esquina',
      'Estacion Saladas',
      'General Alvear',
      'General Paz',
      'Goya',
      'Ifran',
      'Itatí',
      'Ituzaingó',
      'Lavalle',
      'Los Laureles',
      'Mburucuyá',
      'Mercedes',
      'Monte Caseros',
      'Paso de la Patria',
      'Paso de los Libres',
      'Puesto De Isla',
      'Rincon Itaembe',
      'Saladas',
      'San Cosme',
      'San Luis del Palmar',
      'San Martín',
      'San Miguel',
      'San Roque',
      'Santo Tomé',
      'Sauce',
    ],
    'Entre Ríos': [
      'Alcaraz 2do',
      'Alcaraz Norte',
      'Alcete',
      'Aldea Chaleco',
      'Aldea Maria Luisa',
      'Aldea Protestante',
      'Aldea Santa Maria',
      'Almacen Cristian Schubert',
      'Antonio Tomas',
      'Antonio Tomas Sud',
      'Aranguren',
      'Arroyo Brasilero',
      'Arroyo Burgos',
      'Arroyo Moreira',
      'AYUI (PARADA EMBARCADERO FCGU)',
      'Berduc',
      'Brazo Largo',
      'C. del Uruguay',
      'Calera',
      'Cañada De Las Ovejas',
      'Centro Comunitario Cnia Nue',
      'Colón',
      'Colonia Avellaneda',
      'Colonia Berro',
      'Colonia Celina',
      'Colonia Centenario',
      'Colonia Ensayo',
      'Colonia Loma Negra',
      'Colonia Reffino',
      'Concordia',
      'Costa Grande',
      'Crespo',
      'Diamante',
      'El Pingo',
      'Federación',
      'Federal',
      'Feliciano',
      'Gualeguay',
      'Gualeguaychú',
      'Gualeguaycito',
      'Hernández',
      'Isla del Charigue',
      'Islas del Ibicuy',
      'La Blanqueada',
      'La Paz',
      'Libertador San Martín',
      'María Grande',
      'Nogoyá',
      'Paraná',
      'Pasaje Talavera',
      'Paso Telegrafo',
      'Puiggari',
      'Ramírez',
      'Rosario del Tala',
      'San Benito',
      'San Salvador',
      'Seguí',
      'Strobel',
      'Urdinarrain',
      'Viale',
      'Victoria',
      'Villaguay',
    ],
    Formosa: [
      'Bermejo',
      'Formosa',
      'Gran Guardia',
      'Kilometro 254',
      'Laishi',
      'Matacos',
      'Patiño',
      'Pilagás',
      'Pilcomayo',
      'Pirané',
      'Puesto Aguara',
      'Ramón Lista',
    ],
    Jujuy: [
      'Algarrobal',
      'Antumpa',
      'Cochinoca',
      'Corral De Piedras',
      'Doctor Manuel Belgrano',
      'El Carmen',
      'Humahuaca',
      'La Chinaca',
      'Ledesma',
      'Palpalá',
      'Rinconada',
      'San Antonio',
      'San Pedro',
      'San Pedro De Iruya',
      'San Salvador de Jujuy',
      'Santa Bárbara',
      'Santa Catalina',
      'Sey',
      'Susques',
      'Tilcara',
      'Tumbaya',
      'Valle Grande',
      'Yavi',
    ],
    'La Pampa': [
      'Agua De Torre',
      'Anguil',
      'Atreucó',
      'Caleu Caleu',
      'Catriló',
      'Chacra La Magdalena',
      'Chalileo',
      'Chanilao',
      'Chapaleufú',
      'Chical Co',
      'Conhelo',
      'Curacó',
      'El Malacate',
      'Guatraché',
      'Hucal',
      'La Bilbaina',
      'La Rosa',
      'Lihuel Calel',
      'Limay Mahuida',
      'Loventué',
      'Maracó',
      'Puelén',
      'Quemú Quemú',
      'Rancul',
      'Realicó',
      'Ricardo Lavalle',
      'Santa Aurelia',
      'Santa Rosa',
      'Toay',
      'Trenel',
      'Utracán',
    ],
    'La Rioja': [
      'Alpasinche',
      'Amuschina',
      'Anguinan',
      'Arauco',
      'Carrizal',
      'Castro Barros',
      'Chamical',
      'Chilecito',
      'Comandante Leal',
      'Coronel Felipe Varela',
      'El Calden',
      'El Medano',
      'El Tala',
      'Famatina',
      'General Angel V. Peñaloza',
      'General Belgrano',
      'General Juan F. Quiroga',
      'General Lamadrid',
      'General Ocampo',
      'General San Martín',
      'Independencia',
      'La Rioja Capital',
      'Rosario Vera Peñaloza',
      'San Blas de los Sauces',
      'Sanagasta',
      'Vinchina',
    ],
    Mendoza: [
      '12 De Octubre',
      'Algarrobal Abajo',
      'Alpatacal',
      'Alto Grande',
      'Barrio Villa Adela',
      'Buena Nueva',
      'Canalejas',
      'Carbometal',
      'Colonia Alvear',
      'Colonia Bombal Y Tabanera',
      'Coquimbito',
      'Corral De Lorca',
      'Cupiles',
      'El Cenizo',
      'General Alvear',
      'General Gutierrez',
      'Gobernador Benegas',
      'Godoy Cruz',
      'Guaymallén',
      'Junín',
      'La Paz',
      'Las Heras',
      'Lavalle',
      'Los Corredores',
      'Luján de Cuyo',
      'Maipú',
      'Malargüe',
      'Media Luna',
      'Mendoza',
      'Ochenta Y Cuatro',
      'Paso De Los Andes',
      'Puesto Los Chañares',
      'Rivadavia',
      'San Carlos',
      'San Martín',
      'San Rafael',
      'Santa Rosa',
      'Tunuyán',
      'Tupungato',
      'Valle De Las Leñas',
      'Villa Hipodromo',
    ],
    Misiones: [
      '2 de Abril',
      '22 DE diciembre',
      '25 de Mayo',
      'Apóstoles',
      'Arroyo Isabel',
      'Bonpland Norte',
      'Cabure',
      'Cainguás',
      'Candelaria',
      'Cataratas Del Iguazu',
      'Concepción',
      'Eldorado',
      'Garupá',
      'General Manuel Belgrano',
      'Guaraní',
      'Iguazú',
      'Leandro N. Alem',
      'Libertador Grl. San Martín',
      'Montecarlo',
      'Oberá',
      'Posadas',
      'San Ignacio',
      'San Javier',
      'San Pedro',
    ],
    Neuquén: [
      'Alianza',
      'Aluminé',
      'Añelo',
      'Arroyito',
      'Buena Esperanza',
      'Catán Lil',
      'Centenario',
      'Challaco',
      'Chos Malal',
      'Collón Curá',
      'Confluencia',
      'Cullin Manzano',
      'Cutral Có',
      'Gente Grande',
      'Huiliches',
      'Isla Victoria',
      'Lácar',
      'Loncopué',
      'Los Lagos',
      'Minas',
      'Neuquén',
      'Ñorquín',
      'Pehuenches',
      'Picún Leufú',
      'Picunches',
      'Planicie Banderita',
      'Plottier',
      'Quila Quina',
      'San Martin de los Andes',
      'Senillosa',
      'Villa El Chocon',
      'Villa La Angostura',
      'Zapala',
    ],
    'Río Negro': [
      '25 de Mayo',
      '6 DE octubre',
      '9 de Julio',
      'Avellaneda',
      'Bahia Creek',
      'Bariloche',
      'Boca De La Travesia',
      'Cascada Los Cantaros',
      'China Muerta',
      'Cinco Saltos',
      'Cipolletti',
      'Conesa',
      'Costa Del Rio Azul',
      'Cuesta Del Ternero',
      'El Bolsón',
      'El Cuy',
      'General Roca',
      'Ingeniero Huergo',
      'Laguna Del Barro',
      'Ñorquincó',
      'Pichi Mahuida',
      'Pilcaniyeu',
      'Puerto Ojo De Agua',
      'San Antonio',
      'Valcheta',
      'Viedma',
    ],
    Salta: [
      'Acambuco',
      'Alfarcito',
      'Anta',
      'Bacoya',
      'Cachi',
      'Cafayate',
      'Cerrillos',
      'Chaguaral',
      'Chicoana',
      'Coronel Juan Solá',
      'El Desmonte',
      'General Enrique Mosconi',
      'General Güemes',
      'Gral. José de San Martín',
      'Guachipas',
      'Iruya',
      'La Caldera',
      'La Candelaria',
      'La Poma',
      'La Viña',
      'Las Mojarritas',
      'Los Andes',
      'Metán',
      'Molinos',
      'Orán',
      'Pozo Cercado',
      'Rivadavia',
      'Rosario de la Frontera',
      'Rosario de Lerma',
      'Salta',
      'San Carlos',
      'San Lorenzo',
      'Santa Victoria',
    ],
    'San Juan': [
      '25 de Mayo',
      '9 de Julio',
      'Albardón',
      'Albarracin',
      'Angaco',
      'Calingasta',
      'Capitan Lazo',
      'Caucete',
      'Chimbas',
      'Colonia Centenario',
      'Colonia Zapata',
      'Dique Toma',
      'Estacion La Rinconada',
      'Iglesia',
      'Jáchal',
      'Pocito',
      'Rawson',
      'Rivadavia',
      'San Juan Capital',
      'San Martín',
      'Santa Lucía',
      'Sarmiento',
      'Ullúm',
      'Valle Fértil',
      'Villa Lerga',
      'Zonda',
    ],
    'San Luis': [
      '13 DE enero',
      '30 DE octubre',
      'Acasape',
      'Adolfo Rodriguez Saa',
      'Aguaditas',
      'Arbol Verde',
      'Ayacucho',
      'Belgrano',
      'Casimiro Gomez',
      'Chacabuco',
      'Coronel Pringles',
      'El Pimpollo',
      'Favelli',
      'General Pedernera',
      'General Urquiza',
      'Gobernador Dupuy',
      'Isla',
      'Junín',
      'La Chilca',
      'La Colina',
      'La Isabel',
      'La Ribera',
      'La Tranca',
      'Libertador Gral. San Martín',
      'San Lorenzo',
      'San Luis',
      'Villa Mercedes',
    ],
    'Santa Cruz': [
      '28 DE noviembre',
      'Aguada A Pique',
      'Cañada De Las Vacas',
      'Cara Mala',
      'Corpen Aike',
      'Deseado',
      'El Zurdo',
      'Lago Argentino',
      'Lago Buenos Aires',
      'Magallanes',
      'Río Chico',
      'Río Gallegos',
      'Rio Turbio',
      'Tapi Aike',
    ],
    'Santa Fe': [
      '9 de Julio',
      'Aldao',
      'Angel Gallardo',
      'Belgrano',
      'Caminera General Lopez',
      'Campo Andino',
      'Campo Redondo',
      'Caraguatay',
      'Caseros',
      'Castellanos',
      'Cerana',
      'Colonia Montefiore',
      'Colonia Reina Margarita',
      'Constitución',
      'Coronel Rodolfo S. Domínguez',
      'Desvio Boero',
      'El Sombrerito',
      'Estacion Christophersen',
      'Firmat',
      'Frontera',
      'Funes',
      'Garay',
      'General López',
      'General Obligado',
      'Granadero Baigorria',
      'Iriondo',
      'La Capital',
      'Las Colonias',
      'Nelson',
      'Rafaela',
      'Reconquista',
      'Roldán',
      'Rosario',
      'San Carlos Norte',
      'San Carlos Sud',
      'San Cristóbal',
      'San Javier',
      'San Jerónimo',
      'San Jerónimo Sud',
      'San Jose',
      'San Justo',
      'San Lorenzo',
      'San Martín',
      'Santa Fe capital',
      'Santo Tomé',
      'Venado Tuerto',
      'Vera',
      'Villa La Ribera',
      'Villani',
    ],
    'Santiago del Estero': [
      '25 DE mayo',
      '9 DE julio',
      'Acos',
      'Aguirre',
      'Ahi Veremos',
      'Alberdi',
      'Algarrobales',
      'Atamisqui',
      'Avellaneda',
      'Balde Pozo',
      'Belgrano',
      'Choya',
      'Copo',
      'El Arbolito',
      'El Bagual',
      'El Barrial',
      'El Cerrito',
      'El Chañar',
      'El Malacara',
      'El Palomar',
      'El Simbolar',
      'Figueroa',
      'General Taboada',
      'Guanaco Sombriana',
      'Guasayán',
      'Jiménez',
      'Juan F. Ibarra',
      'La Banda',
      'La Donosa',
      'Loreto',
      'Los Porongos',
      'Mili',
      'Moreno',
      'Nueva Ceres',
      'Parana',
      'Pellegrini',
      'Pinto',
      'Quebrachos',
      'Rivadavia',
      'Robles',
      'Rumiarco',
      'Salavina',
      'San Martín',
      'Santiago del Estero',
      'Sarmiento',
      'Silípica',
      'Suncho Pozo',
      'Termas de Río Hondo',
      'Vaca Human',
      'Villa General Mitre',
      'Villa Ojo de Agua',
    ],
    'Tierra del Fuego': [
      'Base Aerea Teniente Matienzo',
      'Frigorifico Cap',
      'Isla Gran Malvina',
      'Río Grande',
      'Ushuaia',
    ],
    Tucumán: [
      'Aguilares',
      'Alongo',
      'Anta',
      'Bajo De Los Sueldos',
      'Burruyacú',
      'Bustamante',
      'Chicligasta',
      'Cruz Alta',
      'El Brete',
      'Famaillá',
      'Graneros',
      'Independencia',
      'Juan Bautista Alberdi',
      'La Banda',
      'La Cocha',
      'Leales',
      'Lules',
      'Monteros',
      'Racó',
      'Río Chico',
      'San Miguel de Tucumán',
      'Simoca',
      'Tafí del Valle',
      'Tafí Viejo',
      'Trancas',
      'Yerba Buena',
    ],
  };
